"""Rate limit helpers for admin endpoints."""

from __future__ import annotations

ADMIN_USERS_PER_MINUTE = 30
ADMIN_AUDIT_LOGS_PER_MINUTE = 30
ADMIN_MUTATION_PER_MINUTE = 10
ADMIN_LIST_WINDOW_SECONDS = 60
ADMIN_MUTATION_WINDOW_SECONDS = 60
__all__ = [
    "ADMIN_USERS_PER_MINUTE",
    "ADMIN_AUDIT_LOGS_PER_MINUTE",
    "ADMIN_MUTATION_PER_MINUTE",
    "ADMIN_LIST_WINDOW_SECONDS",
    "ADMIN_MUTATION_WINDOW_SECONDS",
]
